#!/bin/bash

set -euo pipefail

# https://www.rust-lang.org/learn/get-started
# This command installs the following tools:
#   - rustup (the Rust installer and version management tool)
#   - cargo (the Rust build tool and package manager)
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

ZSHRC_LOCAL="$HOME/.zshrc.local"
GENERATED_CODE_SIGNATURE="Generated by anylang-build/project_build/rust/rustup.sh"

if ! grep -q "$GENERATED_CODE_SIGNATURE" "$ZSHRC_LOCAL"; then
    cat << EOS >> "$ZSHRC_LOCAL"
# $GENERATED_CODE_SIGNATURE
[[ -d \$HOME/.cargo ]] && source "\$HOME/.cargo/env"

EOS
fi
